server:
  port: 8888
spring:
  application:
    name: spring-cloud-gateway-sentinel-example
  main:
    allow-bean-definition-overriding: true
  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        # 添加sentinel的控制台地址
        dashboard: 127.0.0.1:8080
        # 指定应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer
        #port: 8719

    gateway:
      discovery:
        locator:
          # 默认为false，设为true开启通过微服务创建路由的功能，即可以通过微服务名访问服务
          # http://localhost:8888/mall-order/order/findOrderByUserId/1
          enabled: false
          #将注册中心的服务名转小写跟路径匹配
#          lower-case-service-id: true
      # 是否开启网关
      enabled: true

      #设置路由：路由id、路由到微服务的uri、断言
      routes:
      - id: info_route  #路由ID，全局唯一，建议配合服务名
        uri: lb://nacos-producer  #lb 整合负载均衡器ribbon,loadbalancer
        predicates:
        - Path=/producer/info
      - id: testgateway_route
        uri: lb://nacos-producer  #lb 整合负载均衡器ribbon,loadbalancer
        predicates:
        - Path=/producer/testgateway*







