server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: spring-cloud-nacos-sentinel-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        # 添加sentinel的控制台地址
        dashboard: 127.0.0.1:8080
        # 指定应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer
        port: 8719
      log:
        dir: ${user.dir}\spring-cloud-nacos-sentinel-consumer\logs\csp
logging:
  level:
    com.nestor.springcloudnacossentinelconsumer.producer: debug
feign:
  client:
    config:
      default:
        loggerLevel: basic
  compression:
    response:
      enabled: true
    request:
      enabled: true
# 开启feign的sentinel限流
  sentinel:
    enabled: true
producer:
  service:
    name: spring-cloud-nacos-sentinel-producer
ribbon:
  eager-load:
    enabled: true
    clients: spring-cloud-nacos-sentinel-producer
  http:
    client:
      enabled: true